blog/urls.py
from blog.views import *
from django.urls import path,include

app_name = "blog"

urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),    
    path('tag/<str:tag_name>',blog_view,name='tag'),    
    path('author/<str:author_username>',blog_view,name='author'),
]  

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar



sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path(r'', include('django.contrib.auth.urls')),    
     path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/',include(debug_toolbar.urls)),
    path('captcha/', include('captcha.urls')),    
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from website.views import *
from django.urls import path,include

app_name = "website"

urlpatterns = [
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name="contact"),
  
]

website/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_date']
    
    def __str__(self):
        return self.name

website/forms.py
from django import forms
from website.models import Contact
from captcha.fields import CaptchaField


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    
    class Meta:
        model = Contact
        fields = '__all__'

website/views.py
from django.shortcuts import render, HttpResponse
from website.forms import ContactForm
from django.contrib import messages


# Create your views here.
def index_view(request):
    return render(request, 'website/index.html')

def about_view(request):
    return render(request, 'website/about.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your ticket was submitted correctly.')
        else:
            messages.add_message(request, messages.ERROR, 'Your ticket did not submit correctly.')
    else:
        form = ContactForm()

    return render(request, 'website/contact.html', {'form': form})

def login_view(request):
    return render(request,'accounts/login.html')
def signup_view(request):
    return render(request,'accounts/signup.html')

templates/website/Portfolio.html
{% load static %}
<section id="portfolio" class="portfolio section">
    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Portfolio</h2>
        <p>What we've share</p>
    </div>
    <!-- End Section Title -->

    <div class="container">
        <div class="isotope-layout" data-default-filter="*" data-layout="masonry" data-sort="original-order">
            <ul class="portfolio-filters isotope-filters" data-aos="fade-up" data-aos-delay="100">
                <li data-filter="*" class="filter-active">All</li>
                <li data-filter=".filter-app">App</li>
                <li data-filter=".filter-product">Card</li>
                <li data-filter=".filter-branding">Web </li>
            </ul>
            <!-- End Portfolio Filters -->

            <div class="row gy-4 isotope-container" data-aos="fade-up" data-aos-delay="200">
                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-app">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-1.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>app 1</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-1.jpg' %}" title="App 1"
                            data-gallery="portfolio-gallery-app" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-product">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-2.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>Card 1</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-2.jpg' %}" title="Product 1"
                            data-gallery="portfolio-gallery-product" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-branding">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-3.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>Web 1</h4>
                        <p> Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-3.jpg' %}" title="Branding 1"
                            data-gallery="portfolio-gallery-branding" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-app">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-4.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>App 2</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-4.jpg' %}" title="App 2"
                            data-gallery="portfolio-gallery-app" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-product">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-5.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>Card 2</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-5.jpg' %}" title="Product 2"
                            data-gallery="portfolio-gallery-product" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-branding">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-6.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>Web 2</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-6.jpg' %}" title="Branding 2"
                            data-gallery="portfolio-gallery-branding" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-app">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-7.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>App 3</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-7.jpg' %}" title="App 3"
                            data-gallery="portfolio-gallery-app" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-product">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-8.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>Card 3</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-8.jpg' %}" title="Product 3"
                            data-gallery="portfolio-gallery-product" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->

                <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-branding">
                    <img src="{% static 'img/masonry-portfolio/masonry-portfolio-9.jpg' %}" class="img-fluid" alt="" />
                    <div class="portfolio-info">
                        <h4>Web 3</h4>
                        <p>Lorem ipsum, dolor sit</p>
                        <a href="{% static 'img/masonry-portfolio/masonry-portfolio-9.jpg' %}" title="Branding 2"
                            data-gallery="portfolio-gallery-branding" class="glightbox preview-link"><i
                                class="bi bi-zoom-in"></i></a>

                    </div>
                </div>
                <!-- End Portfolio Item -->
            </div>
            <!-- End Portfolio Container -->
        </div>
    </div>
</section>

templates/website/Services.html
{% load static %}
<section id="services" class="services section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Services</h2>
        <p>What we do offer</p>
    </div><!-- End Section Title -->

    <div class="container">

        <div class="row gy-4">

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="service-item  position-relative">
                    <div class="icon">
                        <i class="bi bi-cash-stack" style="color: #0dcaf0;"></i>
                    </div>
                    <a href="#" class="stretched-link">
                        <h3>Nesciunt Mete</h3>
                    </a>
                    <p>Provident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure
                        perferendis
                        tempore et consequatur.</p>
                </div>
            </div><!-- End Service Item -->

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="200">
                <div class="service-item position-relative">
                    <div class="icon">
                        <i class="bi bi-calendar4-week" style="color: #fd7e14;"></i>
                    </div>
                    <a href="#" class="stretched-link">
                        <h3>Eosle Commodi</h3>
                    </a>
                    <p>Ut autem aut autem non a. Sint sint sit facilis nam iusto sint. Libero corrupti neque eum hic non
                        ut
                        nesciunt dolorem.</p>
                </div>
            </div><!-- End Service Item -->

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="300">
                <div class="service-item position-relative">
                    <div class="icon">
                        <i class="bi bi-chat-text" style="color: #20c997;"></i>
                    </div>
                    <a href="#" class="stretched-link">
                        <h3>Ledo Markt</h3>
                    </a>
                    <p>Ut excepturi voluptatem nisi sed. Quidem fuga consequatur. Minus ea aut. Vel qui id voluptas
                        adipisci
                        eos earum corrupti.</p>
                </div>
            </div><!-- End Service Item -->

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="400">
                <div class="service-item position-relative">
                    <div class="icon">
                        <i class="bi bi-credit-card-2-front" style="color: #df1529;"></i>
                    </div>
                    <a href="#" class="stretched-link">
                        <h3>Asperiores Commodit</h3>
                    </a>
                    <p>Non et temporibus minus omnis sed dolor esse consequatur. Cupiditate sed error ea fuga sit
                        provident
                        adipisci neque.</p>
                </div>
            </div><!-- End Service Item -->

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="500">
                <div class="service-item position-relative">
                    <div class="icon">
                        <i class="bi bi-globe" style="color: #6610f2;"></i>
                    </div>
                    <a href="#" class="stretched-link">
                        <h3>Velit Doloremque</h3>
                    </a>
                    <p>Cumque et suscipit saepe. Est maiores autem enim facilis ut aut ipsam corporis aut. Sed animi at
                        autem
                        alias eius labore.</p>
                </div>
            </div><!-- End Service Item -->

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="600">
                <div class="service-item position-relative">
                    <div class="icon">
                        <i class="bi bi-clock" style="color: #f3268c;"></i>
                    </div>
                    <a href="#" class="stretched-link">
                        <h3>Dolori Architecto</h3>
                    </a>
                    <p>Hic molestias ea quibusdam eos. Fugiat enim doloremque aut neque non et debitis iure. Corrupti
                        recusandae ducimus enim.</p>
                </div>
            </div><!-- End Service Item -->

        </div>

    </div>

</section>

templates/website/Testimonials.html
{% load static %}
<section id="testimonials" class="testimonials section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Testimonials</h2>
        <p>What they are saying about us</p>
    </div><!-- End Section Title -->

    <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="swiper init-swiper">
            <script type="application/json" class="swiper-config">
          {
            "loop": true,
            "speed": 600,
            "autoplay": {
              "delay": 5000
            },
            "slidesPerView": "auto",
            "pagination": {
              "el": ".swiper-pagination",
              "type": "bullets",
              "clickable": true
            },
            "breakpoints": {
              "320": {
                "slidesPerView": 1,
                "spaceBetween": 40
              },
              "1200": {
                "slidesPerView": 3,
                "spaceBetween": 10
              }
            }
          }
        </script>
            <div class="swiper-wrapper">

                <div class="swiper-slide">
                    <div class="testimonial-item">
                        <img src="{% static 'img/testimonials/testimonials-1.jpg' %}" class="testimonial-img" alt="">
                        <h3>Saul Goodman</h3>
                        <h4>Ceo &amp; Founder</h4>
                        <div class="stars">
                            <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i>
                        </div>
                        <p>
                            <i class="bi bi-quote quote-icon-left"></i>
                            <span>Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit
                                rhoncus.
                                Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at
                                semper.</span>
                            <i class="bi bi-quote quote-icon-right"></i>
                        </p>
                    </div>
                </div><!-- End testimonial item -->

                <div class="swiper-slide">
                    <div class="testimonial-item">
                        <img src="{% static 'img/testimonials/testimonials-2.jpg' %}" class="testimonial-img" alt="">
                        <h3>Sara Wilsson</h3>
                        <h4>Designer</h4>
                        <div class="stars">
                            <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i>
                        </div>
                        <p>
                            <i class="bi bi-quote quote-icon-left"></i>
                            <span>Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid
                                cillum eram
                                malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim
                                culpa.</span>
                            <i class="bi bi-quote quote-icon-right"></i>
                        </p>
                    </div>
                </div><!-- End testimonial item -->

                <div class="swiper-slide">
                    <div class="testimonial-item">
                        <img src="{% static 'img/testimonials/testimonials-3.jpg' %}" class="testimonial-img" alt="">
                        <h3>Jena Karlis</h3>
                        <h4>Store Owner</h4>
                        <div class="stars">
                            <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i>
                        </div>
                        <p>
                            <i class="bi bi-quote quote-icon-left"></i>
                            <span>Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam
                                duis
                                minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.</span>
                            <i class="bi bi-quote quote-icon-right"></i>
                        </p>
                    </div>
                </div><!-- End testimonial item -->

                <div class="swiper-slide">
                    <div class="testimonial-item">
                        <img src="{% static 'img/testimonials/testimonials-4.jpg' %}" class="testimonial-img" alt="">
                        <h3>Matt Brandon</h3>
                        <h4>Freelancer</h4>
                        <div class="stars">
                            <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i>
                        </div>
                        <p>
                            <i class="bi bi-quote quote-icon-left"></i>
                            <span>Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat
                                minim
                                velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore
                                illum
                                veniam.</span>
                            <i class="bi bi-quote quote-icon-right"></i>
                        </p>
                    </div>
                </div><!-- End testimonial item -->

                <div class="swiper-slide">
                    <div class="testimonial-item">
                        <img src="{% static 'img/testimonials/testimonials-5.jpg' %}" class="testimonial-img" alt="">
                        <h3>John Larson</h3>
                        <h4>Entrepreneur</h4>
                        <div class="stars">
                            <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i
                                class="bi bi-star-fill"></i>
                        </div>
                        <p>
                            <i class="bi bi-quote quote-icon-left"></i>
                            <span>Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster
                                veniam enim
                                culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi
                                cillum
                                quid.</span>
                            <i class="bi bi-quote quote-icon-right"></i>
                        </p>
                    </div>
                </div><!-- End testimonial item -->

            </div>
            <div class="swiper-pagination"></div>
        </div>

    </div>

</section>

templates/website/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section id="contact" class="contact section">

    <div class="container section-title" data-aos="fade-up">
        <h2>Contact</h2>
        <p>Contact Us</p>
    </div>

    <div class="container" data-aos="fade" data-aos-delay="100">

        <div class="row gy-4">

            <div class="col-lg-4">
                <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="200">
                    <i class="bi bi-geo-alt flex-shrink-0"></i>
                    <div>
                        <h3>Address</h3>
                        <p>A108 Adam Street, New York, NY 535022</p>
                    </div>
                </div>

                <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
                    <i class="bi bi-telephone flex-shrink-0"></i>
                    <div>
                        <h3>Call Us</h3>
                        <p>+1 5589 55488 55</p>
                    </div>
                </div>

                <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="400">
                    <i class="bi bi-envelope flex-shrink-0"></i>
                    <div>
                        <h3>Email Us</h3>
                        <p>info@example.com</p>
                    </div>
                </div>

            </div>

            <div class="col-lg-8">
                <!-- Display Django messages -->
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}

                <form action="{% url 'website:contact' %}" method="post" data-aos="fade-up" data-aos-delay="200">
                    {% csrf_token %}
                    <div class="row gy-4">
                        <div class="col-md-6">
                            <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
                        </div>

                        <div class="col-md-6">
                            <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
                        </div>

                        <div class="col-md-12">
                            <input type="text" class="form-control" name="subject" placeholder="Subject" required="">
                        </div>

                        <div class="col-md-12">
                            <textarea class="form-control" name="message" rows="6" placeholder="Message"
                                required=""></textarea>
                        </div>
                        <div>
                            {{form.captcha}}
                        </div>
                        <div class="col-md-12 text-center">
                            <button type="submit">Send Message</button>
                        </div>
                    </div>
                </form>

            </div>

        </div>

    </div>

</section>
{% endblock %}

templates/website/latest_post.html
{% load static %}
{% load humanize %}
<section id="recent-posts" class="recent-posts section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Recent Posts</h2>
        <p>Recent Blog Posts<br></p>
    </div><!-- End Section Title -->

    <div class="container">

        <div class="row gy-4">
            {% for post in posts %}

            <div class="col-xl-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
                <article>

                    <div class="post-img">
                        <img src="{{ post.image.url }}" alt="" class="img-fluidd">
                    </div>

                    <p class="post-category">{% for cat in post.category.all %}
                        <a href="{% url 'blog:category' cat_name=cat.name  %}">{{cat.name}}</a>
                        {% if not forloop.last %},
                        {% endif %}
                        {% endfor %}
                    </p>

                    <h2 class="title">
                        <a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
                    </h2>

                    <div class="d-flex align-items-center">
                        <img src="{% static 'img/blog/blog-author.jpg' %}" alt=""
                            class="img-fluid post-author-img flex-shrink-0">
                        <div class="post-meta">
                            <a href="{% url 'blog:author' author_username=post.author.username %}"
                                class="post-author">{{post.author.get_full_name}}</a>
                            <p class="post-date">
                                {{post.published_date|naturaltime}}
                            </p>
                        </div>
                    </div>

                </article>
            </div><!-- End post list item -->
            {% endfor %}

        </div><!-- End recent posts list -->

    </div>

</section>

templates/website/team.html
{% load static %}
<section id="team" class="team section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Team</h2>
        <p>Our Hardworking Team</p>
    </div><!-- End Section Title -->

    <div class="container">

        <div class="row gy-4">
            {% for post in posts %}

            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                <div class="team-member">
                    <div class="member-img">
                        <img src="{{post.image.url}}" class="img-fluidd" alt="">
                        <div class="social">
                            <a href=""><i class="bi bi-twitter-x"></i></a>
                            <a href=""><i class="bi bi-facebook"></i></a>
                            <a href=""><i class="bi bi-instagram"></i></a>
                            <a href=""><i class="bi bi-linkedin"></i></a>
                        </div>
                    </div>
                    <div class="member-info">
                        <a href="{% url 'blog:author' author_username=post.author.username %}">
                            <h4>{{post.author.get_full_name}}</h4>
                        </a>
                        {% for cat in post.category.all %}
                        <a>{{cat.name}}</a>
                        {% if not forloop.last %},
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div><!-- End Team Member -->
            {% endfor %}

        </div>

    </div>

</section>