accounts/urls.py
from accounts.views import *
from django.urls import path,include
from django.contrib.auth import views as auth_views



app_name = 'accounts'

urlpatterns = [
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('signup/',signup_view,name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),
]

blog/urls.py
from blog.views import *
from django.urls import path,include

app_name = "blog"

urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),    
    path('tag/<str:tag_name>',blog_view,name='tag'),    
    path('author/<str:author_username>',blog_view,name='author'),
]  

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar



sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path(r'', include('django.contrib.auth.urls')),    
     path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/',include(debug_toolbar.urls)),
    path('captcha/', include('captcha.urls')),    
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from website.views import *
from django.urls import path,include

app_name = "website"

urlpatterns = [
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name="contact"),
  
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tag = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        ordering = ['-created_date']
        
        
    def __str__(self) -> str:
        return "{} - {}".format(self.title,self.id)
    
    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pid": self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self) :
        return self.name
    
    class Meta:
        ordering = ['-created_date']

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):

    
    class Meta:
        model = Comment
        fields = ['post','name','email','subject','message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post,Comment
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from blog.forms import CommentForm
from django.contrib import messages


def blog_view(request, **kwargs):
    now = timezone.now()
    posts = Post.objects.filter(published_date__lte=now, status=1)
    
    if kwargs.get('cat_name') is not None:
        posts = posts.filter(category__name=kwargs['cat_name'])
        
    if kwargs.get('author_username') is not None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') is not None:
        posts = posts.filter(tag__name__in=[kwargs['tag_name']])
    
        
    paginator = Paginator(posts, 6)
    
    try:
        page_number = request.GET.get('page')
        posts = paginator.page(page_number)  
    except PageNotAnInteger:
        posts = paginator.page(1)  
    except EmptyPage:
        posts = paginator.page(1)  
        
    
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)


def blog_single(request,pid):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your comment was submitted successfully.')
        else:
            messages.error(request, 'There was an error with your submission. Please correct the errors below.')
            
    now = timezone.now()

    post = get_object_or_404(Post, published_date__lte=now, pk=pid, status=1)
    post.counted_views += 1
    post.save()

    posts = Post.objects.filter(status=1, published_date__lte=now).order_by('published_date')
    
    post_ids = list(posts.values_list('id', flat=True))
    current_index = post_ids.index(post.id)

    prev_post = posts[current_index - 1] if current_index > 0 else None
    next_post = posts[current_index + 1] if current_index < len(post_ids) - 1 else None
    
    comments = Comment.objects.filter(post=post.id,)
    form = CommentForm()

    
    context = {
        'post': post,
        'prev_post': prev_post,
        'next_post': next_post,
        'comments' :  comments,
    }
    return render(request,'blog/blog-single.html',context)
    

templates/blog/blog-author.html
{% load static %}
<!-- Blog Author Widget -->
<div class="blog-author-widget widget-item">

    <div class="d-flex flex-column align-items-center">
        <img src="{{post.image.url}}" class="rounded-circle flex-shrink-0" alt="">
        <h4>{{post.author.get_full_name}}</h4>
        <div class="social-links">
            <a href="https://x.com/#"><i class="bi bi-twitter-x"></i></a>
            <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
            <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
            <a href="https://instagram.com/#"><i class="biu bi-linkedin"></i></a>
        </div>

        <p>
            Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat
            voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
        </p>

    </div>
</div><!--/Blog Author Widget -->

templates/blog/blog-category.html
{% load static %}
<!-- Categories Widget -->
<div class="categories-widget widget-item">

    <h3 class="widget-title">Categories</h3>
    {% for name,count in categories.items %}
    <ul>
        <a href="{% url 'blog:category' cat_name=name %}" class="mt-3">
            <p>{{name}}: {{count}}</p>

        </a>
    </ul>

    {% endfor %}

</div><!--/Categories Widget -->

templates/blog/blog-home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

<main class="main">

  <!-- Page Title -->
  <div class="page-title dark-background">
    <div class="container position-relative">
      <h1>Blog</h1>
      <p>Esse dolorum voluptatum ullam est sint nemo et est ipsa porro placeat quibusdam quia assumenda numquam
        molestias.</p>
      <nav class="breadcrumbs">
        <ol>
          <li><a href="{% url 'website:index' %}">Home</a></li>
          <li class="current">Blog</li>
        </ol>
      </nav>
    </div>
  </div><!-- End Page Title -->

  <!-- Blog Posts Section -->
  <section id="blog-posts" class="blog-posts section">

    <div class="container">
      <div class="row gy-4">
        {% for post in posts %}
        <div class="col-lg-4">
          <article>

            <div class="post-img">
              <img src="{{post.image.url}}" alt="" class="img-fluidd">
            </div>

            <p class="post-category">
              {% for cat in post.category.all %}
              <a href="{% url 'blog:category' cat_name=cat.name  %}">{{cat.name}}</a> {% if not forloop.last %},
              {%endif%}
              {% endfor %}
            </p>

            <h5 class="post-counted_view">{{post.counted_views}} views</h5>
            <br>

            <h2 class="title">
              <a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
            </h2>
            <h5 class="content">
              <p>{{post.content|truncatechars:50}}</p>
            </h5>

            <div class="d-flex align-items-center">
              <img src="{{post.image.url}}" alt="" class="img-fluid post-author-img flex-shrink-0">
              <div class="post-meta">
                <a href="{% url 'blog:author' author_username=post.author.username %}"
                  class="post-author">{{post.author.get_full_name}}</a>
                <p class="post-date">
                  {{post.published_date|naturaltime}}
                </p>
              </div>
            </div>

          </article>
        </div><!-- End post list item -->
        {% endfor %}

      </div>
    </div>

  </section><!-- /Blog Posts Section -->

  <!-- Blog Pagination Section -->
  <section id="blog-pagination" class="blog-pagination section">

    <div class="container">
      <div class="d-flex justify-content-center">
        <ul>
          {% if posts.has_previous %}
          <li>
            <a href="?page={{ posts.previous_page_number }}">
              <i class="bi bi-chevron-left"></i>
            </a>
          </li>
          {% endif %}

          {% for i in posts.paginator.page_range %}
          <li>
            <a href="?page={{ i }}" class="{% if posts.number == i %}active{% endif %}">
              {{ i }}
            </a>
          </li>
          {% endfor %}

          {% if posts.has_next %}
          <li>
            <a href="?page={{ posts.next_page_number }}">
              <i class="bi bi-chevron-right"></i>
            </a>
          </li>
          {% endif %}
        </ul>

      </div>
    </div>

  </section><!-- /Blog Pagination Section -->

</main>

{% endblock %}

templates/blog/blog-recent.html
{% load static %}
{% load humanize %}
<!-- Recent Posts Widget -->
<div class="recent-posts-widget widget-item">
    <h3 class="widget-title">Recent Posts</h3>
    {% for post in posts %}
    <div class="post-item">
        <h4><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h4>
        <p>{{post.published_date|naturaltime}}</p>

    </div><!-- End recent post item-->
    {% endfor %}

</div><!--/Recent Posts Widget -->

templates/blog/blog-search.html
{% load static %}
<!-- Search Widget -->
<div class="search-widget widget-item">

    <h3 class="widget-title">Search</h3>
    <form action="">
        <input type="text">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
    </form>

</div><!--/Search Widget -->

templates/blog/blog-single.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

<body class="blog-details-page">


  <main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background">
      <div class="container position-relative">
        <h1>{{post.title}}</h1>

        <nav class="breadcrumbs">
          <ol>
            <li><a href="{% url 'website:index' %}">Home</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li class="current">Blog single</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <div class="container">
      <div class="row">

        <div class="col-lg-8">

          <!-- Blog Details Section -->
          <section id="blog-details" class="blog-details section">
            <div class="container">

              <article class="article">

                <div class="post-img">
                  <img src="{{post.image.url}}" alt="" class="img-fluiddd">
                </div>

                <h2 class="title">{{post.title}}</h2>

                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                        href="#">{{post.author.get_full_name}}</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#">
                        {{post.published_date|naturaltime}}</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a
                        href="#">{{comments|length}} comments</a></li>
                    <li class="d-flex align-items-center">
                      <a href="#">
                        {{post.counted_views}} views</a>
                    </li>

                  </ul>
                </div><!-- End meta top -->

                <div class="content">
                  <p>
                    {{post.content}}
                  </p>


                </div><!-- End post content -->

                <div class="meta-bottom">
                  <i class="bi bi-folder"></i>
                  <ul class="cats">
                    <li><a href="#">Business</a></li>
                  </ul>

                  <i class="bi bi-tags"></i>
                  <ul class="tags">
                    <li><a href="#">Creative</a></li>
                    <li><a href="#">Tips</a></li>
                    <li><a href="#">Marketing</a></li>
                  </ul>
                </div><!-- End meta bottom -->
                <br><br>
                <div class="nav-container">
                  <div
                    class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                    {% if prev_post %}
                    <div class="thumb">
                      <a href="{% url 'blog:single' prev_post.id %}">
                        <img class="img-fluid" src="{{ prev_post.image.url }}" alt="{{ prev_post.title }}" />
                      </a>
                    </div>
                    <div class="details">
                      <a href="{% url 'blog:single' prev_post.id %}">
                        &laquo; Previous: {{ prev_post.title }}
                      </a>
                    </div>
                    {% endif %}
                  </div>
                  <div
                    class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                    {% if next_post %}
                    <div class="details">
                      <a href="{% url 'blog:single' next_post.id %}">
                        Next: {{ next_post.title }} &raquo;
                      </a>
                    </div>
                    <div class="thumb">
                      <a href="{% url 'blog:single' next_post.id %}">
                        <img class="img-fluid" src="{{ next_post.image.url }}" alt="{{ next_post.title }}" />
                      </a>
                    </div>
                    {% endif %}
                  </div>
                </div>


              </article>

            </div>
          </section><!-- /Blog Details Section -->

          <!-- Blog Comments Section -->
          <section id="blog-comments" class="blog-comments section">

            <div class="container">

              <h4 class="comments-count">{{comments|length}} comments</h4>
              {% for comment in comments %}
              <div id="comment-1" class="comment">
                <div class="d-flex">
                  <div class="comment-img"><img src="{% static 'img/blog/comments-1.jpg' %}" alt=""></div>
                  <div>
                    <h5><a href="#">{{comment.name}}</a>
                      <p>{{comment.created_date|naturaltime}}</p>
                      <p>
                        {{comment.message}}
                      </p>
                  </div>

                </div>
              </div>
              {% empty %}
              <p>No comments here. Be the first to share your thoughts!</p>
              {% endfor %}<!-- End comment #1 -->

            </div>

          </section><!-- /Blog Comments Section -->

          <!-- Comment Form Section -->
          <section id="comment-form" class="comment-form section">
            <div class="container">
              {% if not request.user.is_authenticated %}
              <h3>If you want to share your comment, <a
                  href="{% url 'accounts:login' %}?next={% url 'blog:single' pid=post.id %}">Login</a></h3>
              {% else %}
              <form action="{% url 'blog:single' pid=post.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="post" value="{{ post.id }}">

                <h4>Post Comment</h4>
                <p>Your email address will not be published. Required fields are marked * </p>

                <input type="hidden" name="name" value="{{ request.user.username }}">
                <input type="hidden" name="email" value="{{ request.user.email }}">

                <div class="row">
                  <div class="col form-group">
                    <input name="subject" type="text" class="form-control" placeholder="Your subject">
                  </div>
                </div>
                <div class="row">
                  <div class="col form-group">
                    <textarea name="message" class="form-control" placeholder="Your message"></textarea>
                  </div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Post Comment</button>
                </div>
              </form>
              {% endif %}
            </div>
          </section><!-- /Comment Form Section -->

          <!-- /Comment Form Section -->
        </div>
        <div class="col-lg-4 sidebar">

          <div class="widgets-container">
            <!-- Search Widget -->
            <!--/Search Widget -->

            <!-- Blog Author Widget -->
            {% include 'blog/blog-author.html' %}
            <!--/Blog Author Widget -->

            <!-- Categories Widget -->
            {% postcategories %}

            <!--/Categories Widget -->

            <!-- Recent Posts Widget -->
            {% latestpost %}

            <!--/Recent Posts Widget -->

            <!-- Tags Widget -->
            {% include 'blog/blog-tags.html' %}

            <!--/Tags Widget -->

          </div>

        </div>

      </div>
    </div>

  </main>

  {% endblock %}

templates/blog/blog-tags.html
{% load static %}
<!-- Tags Widget -->
<div class="tags-widget widget-item">

    <h3 class="widget-title">Tags</h3>
    {% for tag in post.tag.all %}
    <ul>
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>

    </ul>
    {% endfor %}

</div><!--/Tags Widget -->